# Generated by Django 4.0.6 on 2022-07-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_education_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
