# Generated by Django 4.0.6 on 2022-07-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_skills_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_soft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'categories_softwares',
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_skill',
        ),
        migrations.AlterModelOptions(
            name='category_skill',
            options={'verbose_name_plural': 'categories_skills'},
        ),
        migrations.AddField(
            model_name='softskill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category_soft'),
        ),
    ]
