# Generated by Django 4.0.6 on 2022-07-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_category_soft_rename_category_category_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softskill',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category_soft',
        ),
        migrations.DeleteModel(
            name='Softskill',
        ),
    ]
